# Generated by Django 2.2 on 2019-04-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handicaps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('event', models.CharField(max_length=100)),
                ('par', models.IntegerField()),
                ('rating', models.FloatField()),
                ('slope', models.IntegerField()),
            ],
        ),
    ]
