# Generated by Django 2.2 on 2019-04-30 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handicaps', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_score', models.IntegerField()),
                ('date_played', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handicaps.Course')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handicaps.Player')),
            ],
        ),
    ]
